/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author caiquegl
 */
public class Random extends javax.swing.JFrame {
    public static int intervalo = 1000;
    public static int milissegundos = 1000;

    /**
     * Creates new form Random
     */
    public Random() {
        initComponents();

    Timer cronometro = new Timer();
    TimerTask tarefa = new TimerTask() {
        @Override
        public void run() {
             String value = time.getText();
             int timeLess = Integer.parseInt(value) - 1;
             time.setText(Integer.toString(timeLess));
             if(timeLess == 0){
                 System.out.println("acabou)");
                 intervalo = 0;
                 milissegundos = 0;
                 System.out.println(intervalo);
             }
        }
    };
    cronometro.schedule(tarefa, milissegundos, intervalo);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atRandomRandom = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 600));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        atRandomRandom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/at-esperandoRandom.png"))); // NOI18N
        getContentPane().add(atRandomRandom);
        atRandomRandom.setBounds(0, 90, 260, 310);

        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setText("40");
        getContentPane().add(time);
        time.setBounds(630, 30, 16, 15);

        jButton1.setBackground(new java.awt.Color(185, 77, 7));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/log-out .png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 20, 30, 34);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bg-home.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, -10, 750, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaUsuario TInicial = new TelaUsuario();
        TInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Random.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Random().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atRandomRandom;
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
